import { test, expect } from '@playwright/test';
test('pair, text, approval, reconnect, reload and revoke', async ({ page, request }) => {
 const fixture = await (await request.get('http://127.0.0.1:4101/fixture')).json();
 await page.goto(fixture.url);
 await expect(page.getByRole('heading', { name: '让任务随身' })).toBeVisible();
 expect(new URL(page.url()).hash).toBe('');
 await page.getByRole('button', { name: '连接并申请配对' }).click();
 await expect.poll(async () => (await (await request.get('http://127.0.0.1:4101/pending')).json()).length).toBe(1);
 await expect(page.getByRole('button', { name: '＋ 新建任务' })).toHaveCount(0);
 await request.post('http://127.0.0.1:4101/confirm');
 await expect(page.getByText('已加密连接', { exact: true })).toBeVisible();
 await page.getByRole('button', { name: '＋ 新建任务' }).click();
 await page.getByRole('textbox', { name: '发送消息' }).fill('测试消息');
 await page.getByRole('button', { name: '发送', exact: true }).click();
 await expect(page.getByText('电脑已收到：测试消息', { exact: true })).toBeVisible();
 await page.getByRole('textbox', { name: '发送消息' }).fill('请审批');
 await page.getByRole('button', { name: '发送', exact: true }).click();
 await page.getByRole('button', { name: '仅允许一次' }).click();
 await expect(page.getByText('审批已通过，任务完成。', { exact: true })).toBeVisible();
 const before = await (await request.get('http://127.0.0.1:4101/state')).json();
 await request.post('http://127.0.0.1:4101/disconnect');
 await expect(page.getByText('已加密连接', { exact: true })).toBeVisible({ timeout: 15000 });
 await expect(page.getByText('审批已通过，任务完成。', { exact: true })).toBeVisible();
 expect((await (await request.get('http://127.0.0.1:4101/state')).json()).sends).toBe(before.sends);
 await page.context().setOffline(true);
 await expect(page.getByText('电脑离线 · 自动重连')).toBeVisible();
 await page.context().setOffline(false);
 await expect(page.getByText('已加密连接', { exact: true })).toBeVisible({ timeout: 15000 });
 await request.post('http://127.0.0.1:4101/restart-relay');
 await expect(page.getByText('已加密连接', { exact: true })).toBeVisible({ timeout: 15000 });
 await expect(page.getByText('审批已通过，任务完成。', { exact: true })).toBeVisible();
 expect((await (await request.get('http://127.0.0.1:4101/state')).json()).sends).toBe(before.sends);
 await page.reload();
 await expect(page.getByText('已加密连接', { exact: true })).toBeVisible();
 await page.getByRole('button', { name: '任务 ', exact: false }).last().click();
 await expect(page.getByText('审批已通过，任务完成。', { exact: true })).toBeVisible();
 const cached = await page.evaluate(async () => { const urls: string[] = []; for (const key of await caches.keys()) for (const request of await (await caches.open(key)).keys()) urls.push(new URL(request.url).pathname); return urls; });
 expect(cached.every(path => path.startsWith('/assets/') || ['/icon.svg', '/manifest.webmanifest'].includes(path))).toBe(true);
 await page.screenshot({ path: 'test-results/mobile-' + test.info().project.name + '.png', fullPage: true });
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 await request.post('http://127.0.0.1:4101/revoke');
 await expect(page.getByText('连接被拒绝 · 请检查授权并重新配对')).toBeVisible();
 await expect(page.getByRole('button', { name: '发送', exact: true })).toBeDisabled();
});
